language: java
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
install:
  - mvn -s .travis.maven.settings.xml -version -B
script:
  - mvn -s .travis.maven.settings.xml clean install deploy -P sonatype-oss-release

# Send notification to Slack
notifications:
  slack:
    secure: "F62hKp/hXOO5hX1pdzLA9D2IBjgiAHo+3PF2hToDIdBGXZ0SfQnR4b/R4SgwuimJi3Lx+77UblAQum7rA/aa35L0YY0iENlfKm/qAFX3hP3UhrbQyhqFFYP4GDcjB8zQlzax3fHuYzSdTUtFfk/fZFUHoL8ObNyxGMVLfbsefzzslhUxa7H5O6dlp5MgQp2cW2CS3UEk1GbI57ajiWFcvVRFzuIFIFRSF5PHBGAiqBXfeHMBP6Iy9uvtVRY9gKJYiUhknUZEq9QVAqMdavFmmTMkPAHDsmhvff6Yw72PoYoxQ7bNn4YMsAmQXdnthOXBy96koPZ3QaKibKE9cOLKwQBQ4YqIhF3vzRGcYhYG15zh/TfL45Sgf7Th9+NFvZCifWTLgBbBXjqVMsYWV5tDVxLK+zKG4BD6gkaFVIz36z45LL6Qa1nlJzJmoym0nh8IlK5yUYZDD/17rAqRwvpDrPkwf8jk5P63xDaYOEmNh0PG9GgNlPMCdReYDmBKxUwC8hP2soVAb6qEFIuu0JNxD5iaSQU++iMNTVUlLh39/CazSUlLJ4f8zt0EPXRmf/+HjuJg9pRT14N47hwzenx8YNRcOatqdwR/+bsNZjMtjGEApRnoZJhzMgtUCJqeYVx+DO+XEY6Bv7d0kCVInzH0BQU78hOMUxomOimQow/GxMo="