language: java
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
install:
  - mvn -s .travis.maven.settings.xml -version -B
script:
  - mvn -s .travis.maven.settings.xml clean install deploy -P sonatype-oss-release

# Send notification to Slack
notifications:
  slack:
    secure: "eQikAifFNNhtfmpgIXwFQf2hbRQdH1mxhIkGG4jzuAOH6rp7WUw51H46CLJyQU/ABxDrFzDreiwkdXMqfk3dyKTkV29i4VmqQvZZlZ9P2RGOx+i3OrRkFmsUkw3fWPUjapmr2imtAYaoo4DnWD7xaszzeD7Qxw92j/NhTFGgLmOh90S7wrFZ4IDlLKw/KZcgmc/hYFaHqBq2Tb9cTD7MWMCJBdk5iN85m0mkt/W7AVXxPqEPUuQktxhA+1sXHfRFrL4+WWHnngdyCBtxCpEiv7Gt3Lx/fpElLzB6xXsB4CSIZ2iIjnRuaElioxY+NTA7jqdDANDQqT6CYrixThUlrjOkxo/yUvtods5IxZd9ootQPDV2+BYdLF/5q6kHNq2LBovXkFFBr4UZHu9e2/WvTz0wJHdHto4qda4ur8LqywHKUKaTP9qp4n+H3GmTjbcIgLnjNM4buPJrG5dfg4zqhLoxflOnjlpU0dOg44/rsaLLFt7vVMvTmSFVJdelApRjY5UsU5HxHdaI6nTmhDPPvIRuv4v7eAQRsQFci3cS9cskBrtkVsiGWjV3tOZleDsNEPHr2PNIzSO3C9LhNNBfM2JJouXjQXyeMZ+AuRvwvujg3nyYKTkD50Y2XlYdv7/fd2Hc9EcIxse8WKuydhCiAZ0Bx7tByKCIiCtMr+ujyJQ="